load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_binary(
    name = "fizzbuzz",
    srcs = ["fizzbuzz.go"],
)

go_binary(
    name = "calculator",
    srcs = ["calculator.go"],
)

go_binary(
    name = "countdown",
    srcs = ["countdown.go"],
)

go_binary(
    name = "math",
    srcs = ["math.go"],
)

go_binary(
    name = "range",
    srcs = ["range.go"],
)
