load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_binary(
    name = "fizzbuzz",
    srcs = ["fizzbuzz/main.go"],
)

go_binary(
    name = "calculator",
    srcs = ["calculator/main.go"],
)

go_binary(
    name = "countdown",
    srcs = ["countdown/main.go"],
)

go_binary(
    name = "math",
    srcs = ["math/main.go"],
)

go_binary(
    name = "search_in_rotated_array",
    srcs = ["search_in_rotated_array/main.go"],
)
