py_binary(
    name = "fizzbuzz",
    srcs = ["fizzbuzz.py"],
    python_version = "PY3",
)

py_binary(
    name = "calculator",
    srcs = ["calculator.py"],
    python_version = "PY3",
)

py_binary(
    name = "sets",
    srcs = ["sets.py"],
    python_version = "PY3",
)

py_binary(
    name = "countdown",
    srcs = ["countdown.py"],
    python_version = "PY3",
)

py_binary(
    name = "find_words_in_phone_number",
    srcs = ["find_words_in_phone_number.py"],
    python_version = "PY3",
)
